name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        runner:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-bin: 'false'
          save-if: ${{ github.ref_name == 'main' }}
          cache-all-crates: 'true'

      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: "cargo-nextest"

      - run: cargo build

      - run: cargo nextest run

      - name: Test CLI
        run: |
          cargo build --bin djwavfixer-cli
          
          ./target/debug/djwavfixer-cli ./resources/test/audio_files/original.wav > single_file_output.txt
          ./resources/cli_results/cmp.py single_file_output.txt
          
          ./target/debug/djwavfixer-cli ./resources/test/audio_files > single_dir_output.txt
          ./resources/cli_results/cmp.py single_dir_output.txt
          
          ./target/debug/djwavfixer-cli ./resources/test/audio_files --recursive > recursive_output.txt
          ./resources/cli_results/cmp.py recursive_output.txt  
