name: Lite Checks (Fmt, Clippy, Deny)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lite-checks:
    strategy:
      matrix:
        runner:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - run: cargo fmt --all --check

      - run: cargo clippy --all-targets --all-features -- -D warnings

      - uses: taiki-e/install-action@v2
        with:
          tool: "cargo-deny"

      - run: cargo deny check all
